### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by VAabcjjsw** [pumpkin-ws/HandEyeCalib#1]
当我在进行cmake后运行make -j12会产生大量的报错，以至于无法进行安装，Boost已经安装成功，运行环境是wsl-Ubuntu20.04 on Windows。第一个报错内容为sparkws/spk.hpp: No such file or directory。我将具体的报错附加在了下方。请帮帮我。
[12.txt](https://github.com/pumpkin-ws/HandEyeCalib/files/8681360/12.txt)

**Comment by pumpkin-ws** [comment]
这个应该是由于cmake编译文件里面没有指明c++的版本导致的，我在文件的根目录的CMAKE加入了add_compile_option("-std=c++14")，您这边可以试一下也加上，或者是重新下载源码试试

**Comment by VAabcjjsw** [comment]
我重新下载了源码，依然产生了sparkws/spk.hpp: No such file or directory，您看您方便加一下联系方式吗？

**Comment by pumpkin-ws** [comment]
可以的，13927731410可以加我微信

**Comment by pumpkin-ws** [comment]
安装时有一个没有用的main函数，删除就好，先关闭这个issue，欢迎新问题
